services:
  db:
    image: postgres:14
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - dev.env

  web:
    build: .
    command: /bin/sh -c "./run.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - dev.env
    depends_on:
      - db
      - redis

  redis:
    image: redis:6
    restart: always

  celery:
    depends_on:
      - redis
      - web
    volumes:
      - .:/code
    build: .
    command: /bin/sh -c "./run_celery.sh"
    env_file:
      - dev.env

  celery-beat:
    build: .
    command: /bin/sh -c "./run_celery_beat.sh"
    volumes:
      - .:/code
    depends_on:
      - redis
      - web
    env_file:
      - dev.env