# Generated by Django 4.2.6 on 2023-11-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KyivWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.SmallIntegerField(verbose_name='Temperature')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=150, verbose_name='Description')),
            ],
        ),
    ]
