# Generated by Django 4.2.6 on 2023-11-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyivweather',
            options={'verbose_name': 'Weather', 'verbose_name_plural': 'Weather'},
        ),
        migrations.RemoveField(
            model_name='kyivweather',
            name='id',
        ),
        migrations.AlterField(
            model_name='kyivweather',
            name='date',
            field=models.DateField(primary_key=True, serialize=False, verbose_name='Date'),
        ),
    ]
