# Generated by Django 4.2.6 on 2023-11-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_kyivweather_options_remove_kyivweather_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_id', models.CharField(max_length=36, verbose_name='Celery id')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED')], default='PENDING', max_length=100, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Weather status',
                'verbose_name_plural': 'Weather statuses',
            },
        ),
    ]
