# Generated by Django 4.2.6 on 2023-11-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weathertask'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherUpdateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Update time')),
            ],
            options={
                'verbose_name': 'Weather status',
                'verbose_name_plural': 'Weather statuses',
                'default_permissions': ('change', 'view'),
            },
        ),
    ]
