# Generated by Django 4.2.6 on 2023-11-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_weatherupdatesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherupdatesettings',
            options={'default_permissions': ('change', 'view'), 'verbose_name': 'Weather settings', 'verbose_name_plural': 'Weather settings'},
        ),
    ]
